import React, { useEffect, useState } from 'react';
// Removed useParams as ID will come from props
import { useTranslation } from 'react-i18next';
import { 
  Box, 
  CircularProgress, 
  Alert, 
  Chip, 
  Avatar, 
  Stack, 
  Divider,
  Paper,
  IconButton,
  Collapse,
  Link,
  Button,
  Tooltip,
  Typography,
  Grid
} from '@mui/material';
import { 
  MapPin, 
  Calendar, 
  User,
  Users,
  TextT,
  CaretDown,
  CaretUp,
  ArrowSquareOut,
  Warning,
  CalendarPlus,
  Download,
  ArrowRight
} from '@phosphor-icons/react';
import { AccessibleTypography } from '../../../app/components/AccessibleTypography'; // Corrected import path
// Use correct package name and import fetch function
import { Commitment, fetchCommitmentById, fetchUserByUsername, User as UserType } from '@neurolink/shared';
// Import the configured apiClient
import apiClient from '../../../app/api/apiClient';
// Assuming the API hook will be generated by RTK Query or similar
// import { useGetCommitmentByIdQuery } from '@/shared/features/commitments/commitmentsAPI'; // Placeholder
import { Link as RouterLink } from 'react-router-dom';
import { alpha } from '@mui/material/styles';


// Define props interface
interface CommitmentDetailProps {
  commitmentId: number | string; // Accept number or string
}

// Placeholder hook updated to use apiClient and fetchCommitmentById
const useGetCommitmentByIdQuery = (id: number | string | undefined) => { // Accept number or string
  const [data, setData] = useState<Commitment | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  useEffect(() => {
    if (!id) {
        setIsLoading(false);
        setError(new Error("Commitment ID is missing"));
        return;
    }

    // Define the async function to fetch data using apiClient
    const loadCommitment = async () => {
      setIsLoading(true);
      setError(null);
      try {
        // Use the imported apiClient and fetchCommitmentById function
        const result = await fetchCommitmentById(apiClient, id);
        setData(result);
      } catch (e) {
        if (e instanceof Error) {
          setError(e);
        } else {
          console.error("Caught a non-Error object:", e);
          setError(new Error('An unknown error occurred while fetching commitment details.'));
        }
      } finally {
        setIsLoading(false);
      }
    };

    loadCommitment(); // Call the async function

  }, [id]); // Dependency array includes the id

  return { data, isLoading, error };
};


// Update component definition to accept props
const CommitmentDetail: React.FC<CommitmentDetailProps> = ({ commitmentId }) => {
  const { t } = useTranslation();
  // Use the prop instead of useParams
  const id = commitmentId;
  // Use the updated placeholder hook
  const { data: commitment, isLoading, error } = useGetCommitmentByIdQuery(id);
  const [mapExpanded, setMapExpanded] = useState(true);
  const [participantDetails, setParticipantDetails] = useState<UserType[]>([]);
  const [loadingParticipants, setLoadingParticipants] = useState(false);
  const [participantError, setParticipantError] = useState<string | null>(null);
  const [creatorDetails, setCreatorDetails] = useState<UserType | null>(null);
  const [loadingCreator, setLoadingCreator] = useState(false);
  const [creatorError, setCreatorError] = useState<string | null>(null);

  useEffect(() => {
    const fetchCreatorDetails = async () => {
      if (!commitment?.creatorUsername) return;

      setLoadingCreator(true);
      setCreatorError(null);
      try {
        const creator = await fetchUserByUsername(apiClient, commitment.creatorUsername);
        setCreatorDetails(creator);
      } catch (err) {
        console.error(`Failed to load details for creator ${commitment.creatorUsername}:`, err);
        setCreatorError(t('commitments.detail.creatorLoadError', 'Failed to load creator details.'));
      } finally {
        setLoadingCreator(false);
      }
    };

    const fetchParticipantDetails = async () => {
      if (!commitment?.participants?.length) return;
      
      setLoadingParticipants(true);
      setParticipantError(null);
      
      try {
        const userPromises = commitment.participants.map(participant => 
          fetchUserByUsername(apiClient, participant.username)
        );
        
        const results = await Promise.allSettled(userPromises);
        const userDetails: UserType[] = [];
        
        results.forEach((result, index) => {
          if (result.status === 'fulfilled') {
            userDetails.push(result.value);
          } else {
            console.error(`Failed to load details for ${commitment.participants[index].username}:`, result.reason);
          }
        });
        
        setParticipantDetails(userDetails);
      } catch (err) {
        console.error('Error loading participant details:', err);
        setParticipantError(t('commitments.detail.participantsLoadError', 'Failed to load participant details.'));
      } finally {
        setLoadingParticipants(false);
      }
    };
    
    if (commitment) {
      fetchCreatorDetails();
      fetchParticipantDetails();
    }
  }, [commitment, t]);

  if (isLoading || loadingCreator) {
    return (
      <Box display="flex" justifyContent="center" alignItems="center" sx={{ p: 3, minHeight: 200 }}>
        <CircularProgress size={40} />
      </Box>
    );
  }

  if (error) {
    return (
      <Alert severity="error" sx={{ m: 2 }}>
        {t('commitments.detail.errorLoading', 'Failed to load commitment details.')} {error.message}
      </Alert>
    );
  }

  if (!commitment) {
    return (
      <Alert severity="warning" sx={{ m: 2 }}>
        {t('commitments.detail.notFound', 'Commitment not found.')}
      </Alert>
    );
  }

  const formattedDate = new Date(commitment.dateTime).toLocaleString(undefined, {
    year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit'
  });

  const toggleMap = () => {
    setMapExpanded(!mapExpanded);
  };

  // Generate a specific Google Maps URL for University of Auckland
  const getGoogleMapUrl = (location: string) => {
    // Always use the provided location description
    const query = encodeURIComponent(location);
    return `https://www.google.com/maps/embed/v1/place?key=AIzaSyBFw0Qbyq9zTFTd-tUY6dZWTgaQzuU17R8&q=${query}`;
  };

  const isUniversityLocation = (location: string): boolean => {
    const lowerCaseLocation = location.toLowerCase();
    return lowerCaseLocation.includes('auckland') || 
           lowerCaseLocation.includes('university') || 
           lowerCaseLocation.includes('campus');
  };

  // Function to generate iCalendar file content
  const generateICalendarContent = () => {
    const startTime = new Date(commitment.dateTime);
    // Default duration is 1 hour if not specified
    const endTime = new Date(startTime.getTime() + 60 * 60 * 1000);
    
    // Format dates as required for iCalendar format
    const formatDate = (date: Date) => {
      return date.toISOString().replace(/-|:|\.\d+/g, '');
    };
    
    const startDateFormatted = formatDate(startTime);
    const endDateFormatted = formatDate(endTime);
    
    // Build iCalendar content
    return [
      'BEGIN:VCALENDAR',
      'VERSION:2.0',
      'PRODID:-//Neurolink//Commitments//EN',
      'CALSCALE:GREGORIAN',
      'BEGIN:VEVENT',
      `UID:${commitment.id}@neurolink.app`,
      `DTSTAMP:${formatDate(new Date())}`,
      `DTSTART:${startDateFormatted}`,
      `DTEND:${endDateFormatted}`,
      `SUMMARY:${commitment.title}`,
      `DESCRIPTION:${commitment.description.replace(/\n/g, '\\n')}`,
      commitment.location?.description ? `LOCATION:${commitment.location.description}` : '',
      'END:VEVENT',
      'END:VCALENDAR'
    ].filter(Boolean).join('\r\n');
  };

  // Function to download the calendar event
  const downloadCalendarEvent = () => {
    const icsContent = generateICalendarContent();
    const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
    
    // Create a temporary link and trigger download
    const link = document.createElement('a');
    link.href = window.URL.createObjectURL(blob);
    link.setAttribute('download', `${commitment.title.replace(/\s+/g, '_')}.ics`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <Box sx={{ p: 3 }}>
      {/* Title section */}
      <Box 
        sx={{ 
          mb: 3,
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'flex-start',
          flexWrap: 'wrap',
          gap: 2
        }}
      >
        <AccessibleTypography 
          variant="h4" 
          component="h2"
          sx={{ 
            fontWeight: 600,
            fontSize: '1.75rem'
          }}
        >
          {commitment.title}
        </AccessibleTypography>
        
        <Tooltip title={t('commitments.detail.addToCalendar', 'Add to your calendar')}>
          <Button
            variant="outlined"
            size="small"
            startIcon={<CalendarPlus weight="regular" />}
            onClick={downloadCalendarEvent}
            sx={{ 
              borderRadius: 2,
              textTransform: 'none'
            }}
          >
            {t('commitments.detail.addToCalendar', 'Add to calendar')}
          </Button>
        </Tooltip>
      </Box>

      {/* Main content container - single light shade containing everything */}
      <Paper
        elevation={0}
        sx={{
          p: 3,
          mb: 4,
          borderRadius: 3,
          backgroundColor: theme => theme.palette.mode === 'light' ? '#F7F9FB' : '#1e1e24'
        }}
      >
        {/* Date and Location */}
        <Stack direction="column" spacing={2} sx={{ mb: 3 }}>
          {/* Date */}
          <Box display="flex" alignItems="center">
            <Calendar size={22} weight="regular" style={{ marginRight: 12 }} />
            <Box sx={{ display: 'flex', alignItems: 'center' }}>
              <AccessibleTypography variant="body1" sx={{ color: 'text.primary' }}>
                {formattedDate}
              </AccessibleTypography>
              <IconButton
                size="small"
                onClick={downloadCalendarEvent}
                sx={{ ml: 1 }}
                aria-label={t('commitments.detail.addToCalendar', 'Add to your calendar')}
                title={t('commitments.detail.addToCalendar', 'Add to your calendar')}
              >
                <Download size={16} />
              </IconButton>
            </Box>
          </Box>

          {/* Location */}
          {commitment.location?.description && (
            <Box>
              <Box display="flex" alignItems="center">
                <MapPin size={22} weight="regular" style={{ marginRight: 12 }} />
                <Box sx={{ display: 'flex', alignItems: 'center', flex: 1 }}>
                  <AccessibleTypography variant="body1" sx={{ color: 'text.primary' }}>
                    {commitment.location.description}
                  </AccessibleTypography>
                  
                  <Box sx={{ display: 'flex', ml: 1 }}>
                    <IconButton 
                      onClick={toggleMap} 
                      size="small"
                      aria-label={mapExpanded ? "Hide map" : "Show map"}
                      title={mapExpanded ? "Hide map" : "Show map"}
                    >
                      {mapExpanded ? <CaretUp size={16} /> : <CaretDown size={16} />}
                    </IconButton>
                    
                    <IconButton
                      component="a"
                      href="https://maps.auckland.ac.nz/"
                      target="_blank"
                      rel="noopener noreferrer"
                      size="small"
                      aria-label="Open University of Auckland map in a new tab"
                      title="Open University of Auckland map in a new tab"
                    >
                      <ArrowSquareOut size={16} />
                    </IconButton>
                  </Box>
                </Box>
              </Box>
              
              <Collapse in={mapExpanded}>
                <Box 
                  sx={{ 
                    mt: 2, 
                    ml: 0, 
                    borderRadius: 2, 
                    overflow: 'hidden',
                    border: theme => `1px solid ${theme.palette.divider}`
                  }}
                >
                  <iframe 
                    src={getGoogleMapUrl(commitment.location.description)}
                    title="Location Map"
                    width="100%" 
                    height="400px"
                    style={{ border: 'none' }}
                    loading="lazy"
                    allowFullScreen
                    referrerPolicy="no-referrer-when-downgrade"
                    aria-label="Google Map showing location"
                  />
                  
                  <Box sx={{ p: 2, textAlign: 'center', borderTop: theme => `1px solid ${theme.palette.divider}` }}>
                    <Stack spacing={1.5}>
                      <AccessibleTypography variant="body2" sx={{ color: 'text.secondary', fontStyle: 'italic' }}>
                        Map results may not be 100% accurate. {isUniversityLocation(commitment.location.description) && 
                        "For University of Auckland locations, please use the official campus map."}
                      </AccessibleTypography>
                      
                      <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 1 }}>
                        <Warning size={16} style={{ color: '#f59e0b' }} />
                        <AccessibleTypography variant="body2" sx={{ color: 'text.secondary' }}>
                          For security reasons, we recommend meeting at campus locations instead of other places.
                        </AccessibleTypography>
                      </Box>
                      
                      <Link
                        href="https://maps.auckland.ac.nz/"
                        target="_blank"
                        rel="noopener noreferrer"
                        sx={{ 
                          display: 'flex',
                          alignItems: 'center',
                          justifyContent: 'center',
                          gap: 0.5,
                          mt: 0.5
                        }}
                      >
                        <AccessibleTypography variant="body2">
                          {t('commitments.detail.viewCampusMap', 'View University of Auckland Campus Map')}
                        </AccessibleTypography>
                        <ArrowSquareOut size={14} />
                      </Link>
                    </Stack>
                  </Box>
                </Box>
              </Collapse>
            </Box>
          )}
        </Stack>

        {/* Description label */}
        <Box display="flex" alignItems="center" sx={{ mb: 2 }}>
          <TextT size={20} weight="regular" style={{ marginRight: 8 }} />
          <AccessibleTypography 
            variant="subtitle1" 
            component="h3" 
            sx={{ fontWeight: 600 }}
          >
            {t('commitments.detail.description', 'Description')}
          </AccessibleTypography>
        </Box>

        {/* Description with darker shade */}
        <Paper
          elevation={0}
          sx={{
            p: 2.5,
            borderRadius: 2,
            backgroundColor: theme => theme.palette.mode === 'light' ? '#E5ECF6' : '#2a2a32'
          }}
        >
          <AccessibleTypography 
            variant="body1" 
            sx={{ 
              color: 'text.primary',
              lineHeight: 1.6 
            }}
          >
            {commitment.description}
          </AccessibleTypography>
        </Paper>
      </Paper>

      <Divider sx={{ my: 4 }} />

      {/* Creator and Participants section - single container */}
      <Paper
        elevation={0}
        sx={{
          p: 3,
          borderRadius: 3,
          backgroundColor: theme => theme.palette.mode === 'light' ? '#F7F9FB' : '#1e1e24'
        }}
      >
        {/* Creator section */}
        <Box mb={4}>
          <Box display="flex" alignItems="center" sx={{ mb: 2 }}>
            <User size={20} weight="regular" style={{ marginRight: 8 }} />
            <AccessibleTypography 
              variant="subtitle1" 
              component="h3" 
              sx={{ fontWeight: 600 }}
            >
              {t('commitments.detail.creator', 'Created By')}
            </AccessibleTypography>
          </Box>
          
          <Box sx={{ ml: 2 }}>
            {loadingCreator ? (
              <CircularProgress size={24} />
            ) : creatorError ? (
              <Alert severity="error" sx={{ maxWidth: 'fit-content' }}>
                {creatorError}
              </Alert>
            ) : creatorDetails ? (
              <Stack 
                direction="row" 
                spacing={1.5} 
                alignItems="center" 
                component={RouterLink} 
                to={`/people/${creatorDetails.username}`}
                sx={{ 
                  textDecoration: 'none', 
                  color: 'inherit', 
                  display: 'inline-flex'
                }}
              >
                <Avatar 
                  src={creatorDetails.profilePicture || undefined}
                  sx={{ width: 32, height: 32 }}
                >
                  {!creatorDetails.profilePicture && creatorDetails.username.charAt(0).toUpperCase()} 
                </Avatar>
                <Box>
                  <AccessibleTypography 
                    variant="body1" 
                    sx={{ 
                      fontWeight: 500,
                      lineHeight: 1.2
                    }}
                  >
                    {creatorDetails.displayName || creatorDetails.username}
                  </AccessibleTypography>
                   <Typography variant="caption" color="text.secondary" sx={{ display: 'block', lineHeight: 1.2 }}>
                      @{creatorDetails.username}
                  </Typography>
                </Box>
              </Stack>
            ) : (
              <Typography variant="body1">{commitment.creatorUsername}</Typography> 
            )}
          </Box>
        </Box>

        {/* Participants section */}
        <Box>
          <Box display="flex" alignItems="center" sx={{ mb: 2 }}>
            <Users size={20} weight="regular" style={{ marginRight: 8 }} />
            <AccessibleTypography 
              variant="subtitle1" 
              component="h3" 
              sx={{ fontWeight: 600 }}
            >
              {t('commitments.detail.participants', 'Participants')} ({commitment.participants.length})
            </AccessibleTypography>
          </Box>
          
          {loadingParticipants ? (
            <Box sx={{ ml: 2, py: 2 }}>
              <CircularProgress size={24} />
            </Box>
          ) : participantError ? (
            <Alert severity="error" sx={{ ml: 2 }}>
              {participantError}
            </Alert>
          ) : commitment.participants.length > 0 ? (
            <Grid container spacing={2} sx={{ width: '100%', m: 0 }}>
              {participantDetails.map((user) => {
                const MAX_TAGS_DISPLAYED = 3;
                
                const prioritizedTags = user.tags ? [
                  ...user.tags.filter(tag => ['skill', 'interest', 'programOfStudy'].includes(tag.type)),
                  ...user.tags.filter(tag => !['skill', 'interest', 'programOfStudy'].includes(tag.type))
                ].slice(0, MAX_TAGS_DISPLAYED) : [];
                
                return (
                  <Grid item xs={12} sm={12} md={6} key={user.id || user.username} sx={{ display: 'flex' }}>
                    <Paper
                      elevation={0}
                      sx={(theme) => ({ 
                        p: 2.5,
                        borderRadius: 3,
                        border: `1px solid ${theme.palette.divider}`,
                        height: '100%',
                        width: '100%',
                        display: 'flex',
                        flexDirection: 'column'
                      })}
                    >
                      {/* User header with avatar and name */}
                      <Stack direction="row" spacing={1.5} sx={{ alignItems: 'flex-start', mb: 1 }}>
                        <Avatar 
                          component={RouterLink}
                          to={`/people/${user.username}`}
                          src={user.profilePicture || undefined}
                          sx={{ width: 40, height: 40, cursor: 'pointer' }}
                        />
                        <Box sx={{ flexGrow: 1, overflow: 'hidden' }}>
                          <Link 
                            component={RouterLink} 
                            to={`/people/${user.username}`}
                            color="inherit"
                            underline="hover"
                            sx={{ display: 'block' }}
                          >
                            <AccessibleTypography 
                              variant="subtitle2" 
                              sx={{ 
                                fontWeight: 500, 
                                fontSize: '0.875rem', 
                                whiteSpace: 'nowrap', 
                                overflow: 'hidden', 
                                textOverflow: 'ellipsis' 
                              }}
                            >
                              {user.displayName}
                            </AccessibleTypography>
                          </Link>
                          <Typography variant="caption" color="text.secondary" sx={{ fontSize: '0.75rem' }}>
                            @{user.username}
                          </Typography>
                        </Box>
                        
                        <Button
                          component={RouterLink}
                          to={`/people/${user.username}`}
                          size="small"
                          variant="text"
                          endIcon={<ArrowRight size={16} />}
                          sx={{ 
                            borderRadius: '20px', 
                            px: 1.5,
                            py: 0.3,
                            fontSize: '0.75rem',
                            alignSelf: 'flex-start',
                            flexShrink: 0,
                            minWidth: 'auto'
                          }}
                        >
                          {t('commitments.detail.viewProfile', 'View')}
                        </Button>
                      </Stack>
                      
                      {/* Tags Section */}
                      {prioritizedTags.length > 0 && (
                        <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 0.5, mt: 1, mb: user.bio ? 1 : 0 }}>
                          {prioritizedTags.map((tag) => (
                            <Chip
                              key={`${tag.type}-${tag.value}`}
                              label={tag.value}
                              size="small"
                              sx={{ fontSize: '0.7rem' }}
                            />
                          ))}
                        </Box>
                      )}
                      
                      {/* Bio in card */}
                      {user.bio && (
                        <Paper 
                          elevation={0} 
                          sx={(theme) => ({ 
                            p: 1.2, 
                            bgcolor: theme.palette.background.paper,
                            border: `1px solid ${theme.palette.divider}`,
                            borderRadius: '8px',
                            mb: 1,
                            fontSize: '0.8rem'
                          })}
                        >
                          <Typography variant="body2" color="text.primary" sx={{ 
                            fontSize: '0.8rem', 
                            lineHeight: 1.4,
                            display: '-webkit-box',
                            WebkitLineClamp: 3,
                            WebkitBoxOrient: 'vertical',
                            overflow: 'hidden',
                            textOverflow: 'ellipsis'
                          }}>
                            {user.bio}
                          </Typography>
                        </Paper>
                      )}
                      
                      {/* View Full Profile button */}
                      <Button 
                        variant="text" 
                        fullWidth
                        component={RouterLink}
                        to={`/people/${user.username}`}
                        sx={(theme) => ({
                          borderRadius: '8px',
                          py: 0.6,
                          mt: 'auto',
                          bgcolor: alpha(theme.palette.primary.light, 0.1),
                          color: theme.palette.primary.main,
                          fontSize: '0.8rem',
                          '&:hover': {
                            bgcolor: alpha(theme.palette.primary.light, 0.2)
                          }
                        })}
                      >
                        {t('people.viewFullProfile', 'View Full Profile')}
                      </Button>
                    </Paper>
                  </Grid>
                );
              })}
            </Grid>
          ) : (
            <Box sx={{ ml: 2 }}>
              <AccessibleTypography variant="body2" sx={{ color: 'text.secondary', fontStyle: 'italic' }}>
                {t('commitments.detail.noParticipants', 'No participants listed.')}
              </AccessibleTypography>
            </Box>
          )}
        </Box>
      </Paper>
    </Box>
  );
};

export default CommitmentDetail;
